routes/web.php
<?php

use App\Http\Controllers\Auth\ConfirmPasswordController;
use App\Http\Controllers\Auth\EmailVerificationController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\SessionController;
use App\Http\Controllers\Auth\SignUpController;
use App\Http\Controllers\Auth\TwoFactorAuthenticationController;
use App\Http\Middleware\SetUserLocale;
use App\Http\Middleware\VerifyPasswordResetToken;
use App\Livewire\Pages\Dashboard;
use App\Livewire\Pages\Settings;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * The following routes should be localized.
 * These are usually public routes where there is no authenticated user
 * to get their preferred locale from. The browser locale will be used as a default
 * but can be manually overridden by altering the URL
 *
 * Authenticated routes do not need to be localized since the users preferred locale
 * will be used to select the locale
 */
Route::prefix(/* uses guest localization? LaravelLocalization::setLocale())->middleware('localizationRedirect'*/'')->group(function() {

    //
    // Unauthenticated public product routes
    // Route::view('/', 'pages.product.landing')->name('landing');

    /**
     * The guest-middleware group redirects all requests to the dashboard if the user
     * trying to access the route is already authenticated.
     *
     * Use this group for pages that are only supposed to be accessible for guest
     * such as sign-in, forgot-password, etc.
     */
    Route::middleware('guest')->group(function () {

        Route::prefix('signin')->controller(SessionController::class)->group(function () {
            Route::get('/', 'create')->name('signin.create');
            Route::post('/', 'store')->name('signin.store');

            //
            // Challenge view and post request for two factor authentication
            Route::prefix('challenge')->controller(TwoFactorAuthenticationController::class)->group(function () {
                Route::get('/', 'create')->name('two-factor-authentication.create');
                Route::post('/', 'challenge')->name('two-factor-authentication.challenge');
            });
        });

        Route::prefix('signup')->controller(SignUpController::class)->group(function () {
            Route::get('/', 'create')->name('signup.create');
            Route::post('/', 'store')->name('signup.store');
        });

        Route::prefix('forgot-password')->controller(ForgotPasswordController::class)->group(function () {
            Route::get('/', 'create')->name('password.forgot.create');
            Route::post('/', 'store')->name('password.forgot.store');
        });

        Route::prefix('reset-password')->controller(ResetPasswordController::class)->middleware(VerifyPasswordResetToken::class)->group(function () {
            Route::get('/', 'create')->name('password.reset.create');
            Route::post('/', 'store')->name('password.reset.store');
        });
    });
});

/**
 * The email verification routes must be accessible for unauthenticated users and may not have a language prefix.
 * The corresponding resend email route is located within the auth section
 */
Route::get('verify/{user}', [ EmailVerificationController::class, 'create' ])->name('verify.create')->middleware('signed');

/**
 * The auth-middleware group redirects all requests to the sign-in page
 * if the user trying to access the route is not authenticated.
 *
 * After successful authentication the user is being redirected to the
 * intended destination
 */
Route::middleware([ 'auth', SetUserLocale::class ])->group(function () {
    Route::post('/signout', [ SessionController::class, 'destroy' ])->name('signout');

    //
    // Routes for the password confirmation flow
    Route::prefix('confirm-password')->controller(ConfirmPasswordController::class)->group(function () {
        Route::get('/', 'create')->name('password.confirm.create');
        Route::post('/', 'store')->name('password.confirm.store');
    });

    Route::get('settings', Settings::class)->name('settings');
});

Route::get('/', Dashboard::class)->name('dashboard');


/**
 * The following routes are only available on local environments
 * and should never be exposed to the production environment.
 *
 * Add routes to test functionality if necessary.
 * Use the /playground route and the playground-view to test views.
 */
if (app()->isLocal()) {
    Route::view('playground', 'playground');
    Route::get('/abort/{status}', fn (string $status) => abort($status));
}

app/Livewire/SidebarContent.php
<?php

namespace App\Livewire;

use App\Enums\FacilityType;
use App\Enums\ProviderType;
use App\Models\DaycareCenter;
use App\Models\SupervisoryDistrict;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\Http;
use Illuminate\Validation\Rule;
use Illuminate\View\View;
use Livewire\Component;
use Livewire\WithPagination;

class SidebarContent extends Component
{
    use WithPagination;

    /**
     * defines if the sidebar is on the left side
     *
     * @var boolean
     */
    public bool $left;

    /**
     * content Type for changing content of sidebar
     *
     * @var string
     */
    public string $contentType;

    /**
     * defines if the kitas should be shown as grey markers instead of leaving them out
     *
     * @var boolean
     */
    public bool $greyKitas = false;

    /**
     * input of the postal code
     *
     * @var string
     */
    public string $postalCode = '';

    /**
     * input of the district
     *
     * @var string
     */
    public string $district = 'all';

    /**
     * all possible facility types with their color
     *
     * @var array
     */
    public array $facilityTypes;

    /**
     * input when the kita needs to be open
     *
     * @var string
     */
    public string $opens = 'all';

    /**
     * list of possible opening hours
     *
     * @var array
     */
    public array $openingHours;

    /**
     * input when the kita needs to stay open
     *
     * @var string
     */
    public string $closes = 'all';

    /**
     * list of possible closing hours
     *
     * @var array
     */
    public array $closingHours;

    /**
     * input of the educational focus
     *
     * @var string
     */
    public string $educationalFocus = '';

    /**
     * input of the educational features
     *
     * @var string
     */
    public string $educationalFeatures = '';

    /**
     * input of the provider name
     *
     * @var string
     */
    public string $providerName = '';

    /**
     * input of the provider type
     *
     * @var string
     */
    public string $providerType = 'all';

    /**
     * input of the minimum number of places
     *
     * @var string
     */
    public string $minPlaces = '';

    /**
     * input of the maximum number of places
     *
     * @var string
     */
    public string $maxPlaces = '';

    /**
     * input of the minimum age of care
     *
     * @var string
     */
    public string $minAge = '';

    /**
     * input of the maximum age of care
     *
     * @var string
     */
    public string $maxAge = '';

    /**
     * checks if email should be provided
     *
     * @var boolean
     */
    public bool $email = false;

    /**
     * checks if website should be provided
     *
     * @var boolean
     */
    public bool $website = false;

    /**
     * check if mobile number should be provided
     *
     * @var boolean
     */
    public bool $mobile = false;

    /**
     * checks if fax number should be provided
     *
     * @var boolean
     */
    public bool $fax = false;

    /**
     * kita, which details should be shown
     *
     * @var App\Models\DaycareCenter
     */
    public DaycareCenter $kita;

    /**
     * the address used for the circumcircle geocoding
     *
     * @var string
     */
    public string $address;

    /**
     * the range of the circle for the geocoding
     *
     * @var string
     */
    public string $circle;

    /**
     * all filtered Kita Ids for the list
     *
     */
    public array $filterList;

    /**
     * all Kita Ids in the circle
     *
     * @var array
     */
    public array $circleList;

    /**
     * searchinput for name of kita
     *
     * @var string
     */
    public string $kitaName;

    /**
     * contains the timestrings for the opening hours
     *
     * @var array
     */
    public array $times;

    /**
     * specifies if the sidebar is open
     *
     * @var boolean
     */
    public bool $sidebarOpen;

    /**
     * The event listeners
     *
     * @var array
     */
    protected $listeners = [
        'changeContent' => 'changeContent',
        'details' => 'details',
        'filter' => 'filter',
        'addType' => 'addType',
        'removeType' => 'removeType',
        'listing' => 'listing',
        'circleListing' => 'circleListing',
        'resetFilter' => 'resetFilter',
        'updateSidebar' => 'updateSidebar'
    ];

    /**
     * Mounts the component
     *
     * @param boolean $prize
     * @return void
     */
    public function mount(bool $left) : void
    {
        //
        //defines whether the sidebar is located at the left side
        $this->left = $left;

        //
        //the sidebar is initially always closed
        $this->sidebarOpen = false;

        //
        //first content type should be filter
        $this->contentType = 'filter';

        //
        //definig every facility type with its color and its checked property
        $this->facilityTypes = [
            [
                'class' => 'blue',
                'name' => FacilityType::dayCare->name(),
                'type' => FacilityType::dayCare->value,
                'checked' => true,
            ],
            [
                'class' => 'green',
                'name' => FacilityType::forest->name(),
                'type' => FacilityType::forest->value,
                'checked' => true,
            ],
            [
                'class' => 'gold',
                'name' => FacilityType::parentChild->name(),
                'type' => FacilityType::parentChild->value,
                'checked' => true,
            ],
            [
                'class' => 'red',
                'name' => FacilityType::parentInitiative->name(),
                'type' => FacilityType::parentInitiative->value,
                'checked' => true,
            ],
        ];

        //
        //getting the opening and the closing hours
        $open = [];
        $close = [];
        foreach (DaycareCenter::whereNot('opening_hours', null)->select('opening_hours')->distinct()->get() as $kita) {
            $openingHours = explode(';', $kita->opening_hours);
            foreach ($openingHours as $hours) {
                preg_match('/([^\d]+)\s?(.+)(-)(.+)/i', $hours, $split);
                if (!in_array($split[2], $open)) {
                    $open = array_merge($open, [$split[2]]);
                }
                if (!in_array($split[4], $close)) {
                    $close = array_merge($close, [$split[4]]);
                }
            }
        }
        sort($open);
        sort($close);
        $this->openingHours = $open;
        $this->closingHours = $close;

        //
        //provider name and type that include every kita
        $this->providerName = '';
        $this->providerType = 'all';

        //
        //setting the number of places
        $this->minPlaces = '';
        $this->maxPlaces = '';


        //
        //ages that include every kita
        $this->minAge = '';
        $this->maxAge = '';

        //
        //none of the checkboxes for the information that should be provided should be checked
        $this->email = false;
        $this->website = false;
        $this->mobile = false;
        $this->fax = false;


        //
        //the addressinput is empty
        $this->address = '';

        //
        //the initial circle radius is set to 500 meters
        $this->circle = '0.5';


        //
        //the initial list consists of all kitas
        $this->filterList = ['all'];

        //
        //the initial circle doesnt exist
        $this->circleList = ['all'];

        //
        //nameinput for kita is empty
        $this->kitaName = '';
    }


    /**
     * Updates the fields when the content changes
     *
     * @return void
     */
    public function updated(string $property) : void
    {
        if (str_contains($property, 'facilityType')) {
            $this->emit('filter', $property, $this->facilityTypes, $this->left);

            $this->validate();

            $this->dispatchBrowserEvent('filterTypes', ['types' => $this->facilityTypes]);
        } else if ($property === 'greyKitas') {
            $this->emit('filter', $property, $this->$property, $this->left);

            $this->validate();

            $this->dispatchBrowserEvent('greyKitas', ['show' => $this->greyKitas]);
        } else if ($this->contentType === 'filter') {
            $this->emit('filter', $property, $this->$property, $this->left);

            $this->validate();

            $properties = [
                'district' => $this->district,
                'postalCode' => $this->postalCode,
                'facilityTypes' => $this->facilityTypes,
                'opens' => $this->opens,
                'closes' => $this->closes,
                'educationalFocus' => $this->educationalFocus,
                'educationalFeatures' => $this->educationalFeatures,
                'providerName' => $this->providerName,
                'providerType' => $this->providerType,
                'minPlaces' => $this->minPlaces,
                'maxPlaces' => $this->maxPlaces,
                'minAge' => $this->minAge,
                'maxAge' => $this->maxAge,
                'email' => $this->email,
                'website' => $this->website,
                'mobile' => $this->mobile,
                'fax' => $this->fax
            ];
            $this->emit('filtering', $properties);
        } else if ($this->contentType === 'umkreis') {
            $this->emit('filter', $property, $this->$property, $this->left);

            $this->validateOnly($property);
        } else {
            $this->emit('filter', $property, $this->$property, $this->left);

            $this->validateOnly($property);
        }
    }

    /**
     * Updates the page when content changes
     *
     * @return void
     */
    public function updatedKitaName() : void
    {

resources/views/pages/dashboard.blade.php
@push('styles')
    <style>
        .dot {
            height: 10px;
            width: 10px;
            border-radius: 50%;
            display: inline-block;
        }

        .blue {
            background-color: rgba(42,129,203,0.6);
        }
        .blue div {
            background-color: rgba(42,129,203,1);
        }

        .green {
            background-color: rgba(42,173,39,0.6);
        }
        .green div {
            background-color: rgba(42,173,39,1);
        }

        .gold {
            background-color: rgba(255,211,38,0.6);
        }
        .gold div {
            background-color: rgba(255,211,38,1);
        }

        .red {
            background-color: rgba(203,43,62,0.6);
        }
        .red div {
            background-color: rgba(203,43,62,1);
        }

        .grey {
            background-color: rgba(123,123,123,0.3);
        }
        .grey div {
            background-color: rgba(123,123,123,0.7);
        }

        .marker-cluster {
            background-clip: padding-box;
            border-radius: 20px;
        }
        .marker-cluster div {
            width: 30px;
            height: 30px;
            margin-left: 5px;
            margin-top: 5px;

            text-align: center;
            border-radius: 15px;
            font: 12px "Helvetica Neue", Arial, Helvetica, sans-serif;
        }
        .marker-cluster span {
            line-height: 30px;
        }

        .legend {
            line-height: 18px;
            background-color: rgba(255,255,255,0.8);
            padding: 6px 8px;
            box-shadow: 0 0 15px rgba(0,0,0,0.2);
            border-radius: 5px;
            z-index: 40;
        }
        .legend i {
            width: 14px;
            height: 14px;
            float: left;
            margin-top: 2px;
            margin-bottom: 2px;
            margin-right: 8px;
            opacity: 0.7;
        }
        .info {
            padding: 6px 8px;
            font: 14px/16px Arial, Helvetica, sans-serif;
            background: white;
            background: rgba(255,255,255,0.8);
        }

        @media (max-width: 639px) {
            .legend {
                margin-bottom: 20px !important;
            }
        }


        @media (max-width: 400px) {
            .legend {
                margin-bottom: 40px !important;
            }
        }

        .leaflet-right {
            z-index: auto;
        }

    </style>
@endpush
<div>
    <x-sidebar.index>
        <x-slot:contentLeft>

            @livewire('sidebar-content', ['left' => true])

        </x-slot>

        <x-slot:contentBottom>

            @livewire('sidebar-content', ['left' => false])

        </x-slot>

        <div id="map" class="h-full z-10" wire:ignore></div>
    </x-sidebar.index>
</div>

@push('scripts')
    <script src="https://api.mapbox.com/mapbox.js/v3.3.1/mapbox.js"></script>
    <script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>
    <script src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
    <script> document.addEventListener("DOMContentLoaded", (event) => {
        Modal("intro-modal");
    }) </script>
    <script> const api = <?php echo json_encode(config('app.mapbox_token')); ?> </script>
    <script> var kitas = <?php echo json_encode($this->getJsonKitas()); ?>; </script>
    <script> const kitaTypes = <?php echo json_encode($kitaTypes); ?>; </script>
    <script>
        var resized = false;
        window.addEventListener('resize', function () {
            if (resized) {
                setTimeout(() => {
                    resized = false;
                }, 500);

            } else {
                setTimeout(() => {
                    resized = true;
                    window.dispatchEvent(new Event('resize'));
                }, 500);

            }
        });
    </script>
    <script>
        window.addEventListener('updated', event => {
            kitas = event.detail.kitas;
            recalculateKitas();
        })
    </script>
    <script>
        window.addEventListener('filterTypes', event => {
            removeOverlay(event.detail.types);
        })
    </script>
    <script>
        window.addEventListener('greyKitas', event => {
            removeGreyKitas(event.detail.show);
        })
    </script>
    <script>
        window.addEventListener('listClick', event => {
            switch (event.detail.color) {
                case 'blue':
                    openBluePopup(event.detail.lng, event.detail.lat);
                    break;
                case 'red':
                    openRedPopup(event.detail.lng, event.detail.lat);
                    break;
                case 'green':
                    openGreenPopup(event.detail.lng, event.detail.lat);
                    break;
                default:
                    openGoldPopup(event.detail.lng, event.detail.lat);
                    break;
            }
        })
    </script>
    <script>
        window.addEventListener('circleClick', event => {
            calculateCircle(event.detail.lng, event.detail.lat, event.detail.radius, event.detail.markerPopup);
            window.dispatchEvent(new Event('closeSidebar'));
        })
    </script>
    <script>
        window.addEventListener('circleDelete', event => {
            deleteCircle();
        })
    </script>
    <script>
        window.addEventListener('deleteFilter', event => {
            deleteFilter();
        })
    </script>
    <script type="text/javascript" src="{{ asset('map/map.js') }}"></script>
@endpush

resources/views/pages/settings.blade.php
<div>

    {{-- Title --}}
    <x-title>{{ trans('settings.title') }}</x-title>

    {{-- Two Factor Authentication --}}
    <livewire:pages.settings.two-factor-authentication />
</div>